name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up latest Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r dev-requirements.txt

      - name: Install Node.js dependencies
        working-directory: app/static
        run: npm install

      - name: Test with pytest
        run: |
          pytest

      - name: Test with ESLint
        working-directory: app/static
        run: |
          ./node_modules/.bin/eslint ./js/
